### ISSUE TITLE
Upstream docs for Time resource corrupted

### ISSUE THREAD

**Issue by toriancrane** [pulumi/pulumi-terraform-bridge#1547] opened 2023-11-29 15:09 UTC
### What happened?

A user submitted [an issue](https://github.com/pulumi/docs/issues/11564) asking for clarity around what the [`time` resource](https://www.pulumi.com/registry/packages/time/) does.

It was found that the upstream docs for this resource was corrupted. Per Luke:

> The content from [here](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating) should have been available at https://www.pulumi.com/registry/packages/time/api-docs/rotating/. 

### Example

Compare the contents of the [upstream docs](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating) with [Pulumi docs](https://www.pulumi.com/registry/packages/time/api-docs/rotating/).

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2024-05-15 21:22
Alright. So... it turns out this is not actually a bug but intentional behavior.

When a top-level resource Description contains the word, "Terraform", we [remove the top level description from the resource docs and emit a warning during schemagen](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/docs.go#L2068).

Notice how this is true for not only the [time_rotating](https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/rotating) resource, but all resources in this provider.

The reason for this behavior is that we cannot guarantee that a 1:1 translation of "T/terraform" --> "P/pulumi" actually makes sense in the context of a freeform doc.

The fix for this issue is a provider-level `docsEditRule` to fix up the top-level Descriptions.

I'm going to close this issue as working by design, but am happy to help out with any fixes to the pulumi-time provider.

**Closed by guineveresaenger** 2024-05-15 21:22 UTC
Labels: kind/bug, resolution/by-design, area/docsgen
