### ISSUE TITLE
TF bridge applies defaults and validates config in different order to terraform causing conflicts

### ISSUE THREAD

**Issue by VenelinMartinov** [pulumi/pulumi-terraform-bridge#1546] opened 2023-11-29 16:08 UTC
### What happened?

During the investigation of https://github.com/pulumi/pulumi-azuredevops/issues/66, I noticed that we seem to first apply config defaults and then validate the config, in contrast to tf, which seems to do it in reverse. More details here: https://github.com/pulumi/pulumi-azuredevops/issues/66#issuecomment-1829880996

This causes conflicts, for example with `RequiredWith` - we apply defaults which then don't pass the `RequiredWith` validation. This doesn't cause issues in tf itself, since they only validate user set config for these. We are implementing a workaround in https://github.com/pulumi/pulumi-terraform-bridge/pull/1543 but the issue could be avoided.

One reason we probably do it is that we have defaults on top of the tf defaults, like resource names, which are required in order to pass the tf config validation.

We might want to instead split the default application in two and apply tf defaults after doing the config validation.

### Example

https://github.com/microsoft/terraform-provider-azuredevops/blob/8ab3a0d049ae55e179cd7ed3389f761489ce4228/azuredevops/internal/service/git/resource_git_repository.go#L124C7-L124C7

In `pulumi-azuredevops` we have this https://github.com/pulumi/pulumi-azuredevops/issues/66.
It is caused by the fact we apply the default "" before passing to the validation. TF does not have the problem since it does the reverse.

### Output of `pulumi about`

.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by VenelinMartinov** [comment] 2023-11-29 18:02
I believe this is also related: https://github.com/pulumi/pulumi-azuredevops/issues/38

**Comment by VenelinMartinov** [comment] 2023-11-30 16:12
As discussed in https://github.com/pulumi/pulumi-terraform-bridge/pull/1543#issuecomment-1832324735

In order to maintain backwards compatibility for user programs we'd need to **sometimes** apply TF defaults **BEFORE** as well validation - specifically in the instances where not applying it would break a `RequiredWith` validation, which would have passed previously.

Example:
A, RequiredWith(B), Default "blah"
B, RequiredWith(A),

The user could have specified {B: 3}, which would not pass in TF but would pass with us since that would produce {A: blah, B:3}.


I don't believe there are any similar concerns with `ConflictsWith` - the new validation logic would be pass a strict superset of what passed before.

We might also need something similar for `ExactlyOneOf`, for example:
A, ExactlyOneOf(A, B), Default "blah"
B, ExactlyOneOf(A,B),

An empty user input would NOT have passed in TF but would have passed in pulumi since that'd translate to {A: "blah"} but with the new logic this would fail.

**Comment by t0yv0** [comment] 2023-12-13 21:10
@lukehoban mentioned this is the top bridged provider issue possibly. I was curious so I started running some queries. 

RequiredWith and ConflictsWith seem to be in the same bucket of issues caused by this ordering mismatch.

Rough GitHub search yielded this:

https://github.com/pulumi/pulumi-aws/issues/1027
https://github.com/pulumi/pulumi-aws/issues/1184
https://github.com/pulumi/pulumi-aws/issues/1209
https://github.com/pulumi/pulumi-aws/issues/1531
https://github.com/pulumi/pulumi-aws/issues/1605
https://github.com/pulumi/pulumi-azure/issues/860
https://github.com/pulumi/pulumi-azuredevops/issues/33
https://github.com/pulumi/pulumi-azuredevops/issues/66
https://github.com/pulumi/pulumi-docker/issues/401
https://github.com/pulumi/pulumi-gcp/issues/212
https://github.com/pulumi/pulumi-gcp/issues/227
https://github.com/pulumi/pulumi-gcp/issues/273
https://github.com/pulumi/pulumi-gcp/issues/505
https://github.com/pulumi/pulumi-gcp/issues/560
https://github.com/pulumi/pulumi-gcp/issues/631
https://github.com/pulumi/pulumi-gcp/issues/714
https://github.com/pulumi/pulumi-gitlab/issues/128
https://github.com/pulumi/pulumi-newrelic/issues/87
https://github.com/pulumi/pulumi-okta/issues/202
https://github.com/pulumi/pulumi-snowflake/issues/11
https://github.com/pulumi/pulumi-terraform-bridge/issues/1095
https://github.com/pulumi/pulumi-terraform-bridge/issues/15
https://github.com/pulumi/pulumi-terraform-bridge/issues/1546
https://github.com/pulumi/pulumi-terraform-bridge/issues/1546
https://github.com/pulumi/pulumi-terraform-bridge/issues/309
https://github.com/pulumi/pulumi-terraform-bridge/issues/384
https://github.com/pulumi/pulumi-terraform-bridge/issues/540
https://github.com/pulumi/pulumi/issues/3621
https://github.com/pulumi/pulumi/issues/5586
https://github.com/pulumi/pulumi/issues/6155
https://github.com/pulumi/pulumi/issues/6842
https://github.com/pulumi/pulumi/issues/7535
https://github.com/pulumi/pulumi/issues/7697
https://github.com/pulumi/pulumi/issues/8638

I've also tried

```
select i.issue_url, i.created_at as time, i.state, i.labels,  i.reactions_plus_one, i.*

from

COMMUNITY.DIM_GITHUB_ISSUE i


where (i.body like '%conflicts with%'  or i.body like '%all of % must be specified"%')
and body not like '%Bumps%'
and labels not like '%dependencies%'
and org = 'pulumi'

order by i.state desc, i.created_at desc;
```

This query is overshooting a bit by finding irrelevant issues but it found 74 issues total (21 open). For the closed issues if they're indeed pertinent to this more likely than not we deployed a workaround rather than root causing.

**Comment by t0yv0** [comment] 2023-12-15 15:57
We did a mini-design session and I believe Venelin has a viable way forward here that's fairly incremental/surgical and worth the risk. 

https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfbridge/provider.go#L656

We have this currently:

```
	rescfg := MakeTerraformConfigFromInputs(p.tf, inputs)
	warns, errs := p.tf.ValidateResource(tfname, rescfg)
```

But it can become this:

```
	warns, errs := p.tf.ValidateResource(tfname, MakeTerraformConfigFromInputs(p.tf., inputs, Opts{ApplyDefaults: PulumiOnly}))
	rescfg := MakeTerraformConfigFromInputs(p.tf, inputs)
```

In our conversation we were making an explicit distinction between TF defaults and Pulumi-level defaults such as auto-names here as it sounds like in some cases such as autonames Pulumi defaults need to be applied before validating with TF.

Similar discussion in https://github.com/pulumi/pulumi-terraform-bridge/issues/1095 - things are a bit different in Plugin Framework world and less in need of changing at the moment.

**Comment by VenelinMartinov** [comment] 2023-12-18 13:17
I found some interesting notes about the bridge architecture while digging into this:

https://github.com/pulumi/pulumi-terraform-bridge/blob/bef42c24d09aa958584908e012d8583ae21fd8bd/pkg/tfbridge/schema.go#L166-L172

I don't think this issue completely solves the problem the notes talk about since ConflictsWith and ExactlyOneOf are also taken into account when applying pulumi-level defaults, not just tf ones.

Noting it here since it might be of some interest.

**Comment by VenelinMartinov** [comment] 2023-12-18 15:54
While looking into moving the TF default application I also tested removing it entirely - I'm not sure why we need to apply these defaults since TF already does that.

Looks like we add them to the `__defaults` list and the note in the bridge suggests that that is in order to propagate non-deterministic defaults from the olds values:
https://github.com/pulumi/pulumi-terraform-bridge/blob/bef42c24d09aa958584908e012d8583ae21fd8bd/pkg/tfbridge/schema.go#L128-L135
I wonder what TF does with such defaults.

**Comment by t0yv0** [comment] 2023-12-20 15:19
This is a relatively big leap here that "applying TD defaults is not necessary". What redundant mechanism is applying these defaults then, in the bridged provider?

**Comment by VenelinMartinov** [comment] 2023-12-21 16:03
The TF provider applies the defaults, I don't think we have to do that before passing to the TF provider.
The one difference is that this will mean that the properties with a TF default will no longer be added to the `__defaults` list. I believe this should be fine as TF doesn't keep such a list of defaults.

I have not done this change as part of the PR and I am not sure sure there's any benefits to doing it. I just thought it's interesting that we are doing something which seems redundant.

Actually, I think there might be one functional change related to a TF default changing. I have not tested this but it sounds like that's what should happen.

With our current code if a resource is provisioned with a certain version of the TF provider, we'll save the defaults in the state and according to the notes, reapply them next time we compute the state if we don't have input for the same properties.
If the TF default changes this should mean that users will not pick up that change.

Example:
```
// old TF schema:
Res(A, Schema={Prop1: {Default:A}, Prop2:{}})
// user code:
A(Prop2=C)
// corresponding state:
A(Prop1=A, Prop2=C)

// TF schema changes:
Res(A, Schema={Prop1:{Default:B}, Prop2:{}})
// user does not change the code
A(Prop2=C)

// with current behaviour we should get the same state:
A(Prop1=A, Prop2=C)
// with proposed new behaviour we will get a diff in Prop1:
A(Prop1=B, Prop2=C)
```

I am not sure if this is indeed desired and have not tested what'd happen in TF land.

**Comment by t0yv0** [comment] 2023-12-21 16:48
> The TF provider applies the defaults

Where does this happen? Code references?

**Comment by iwahbe** [comment] 2024-01-04 14:18
Closed by https://github.com/pulumi/pulumi-terraform-bridge/pull/1583

**Closed by iwahbe** 2024-01-04 14:18 UTC
Labels: size/M, resolution/fixed, kind/bug, area/tfbridge
