### ISSUE TITLE
`pulumi-aws` 5.22.0 and above keep updating `aws:route53/resolverEndpoint:ResolverEndpoint` even when there's nothing to update

### ISSUE THREAD

**Issue by aureq** [pulumi/pulumi-terraform-bridge#791] opened 2023-01-03 03:01 UTC
### What happened?

As reported by a customer in Zendesk [#2189](https://pulumi.zendesk.com/agent/tickets/2189)

Running the Python program below, the provider always update the `aws:route53/resolverEndpoint:ResolverEndpoint` resources even when there's no code changes.

During the preview, the diff taken from from the Pulumi service is like this
![image](https://user-images.githubusercontent.com/1161681/210293766-7f90cafd-fba3-4fe8-a8b8-df2b1e0fe702.png)

When applying the update, which takes 6m30s, the diff from the Pulumi service is this
![image](https://user-images.githubusercontent.com/1161681/210293900-e10be36d-e2c9-4a17-85b4-e49a55acbb4e.png)

But downgrading to 5.21.1 and applying the update, everything is then fine and the diff is a lot cleaner.
![image](https://user-images.githubusercontent.com/1161681/210294137-784f3d3e-9b49-4458-b197-2b73d53e5ced.png)

After trying with different versions, here are the versions affected:
- [5.20.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.20.0): ok, no updates
- [5.21.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.21.0): ok, no updates
- [5.21.1](https://github.com/pulumi/pulumi-aws/releases/tag/v5.21.1): ok, no updates
- [5.22.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.22.0): NOT ok, performing unnecessary update
- [5.23.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.23.0): NOT ok, performing unnecessary update
- [5.25.0](https://github.com/pulumi/pulumi-aws/releases/tag/v5.25.0): NOT ok, performing unnecessary update

### Steps to reproduce

Follow the steps below to easily reproduce this issue:

1. Create a new Pulumi application (aws-python)
2. Paste the code provided below
3. In a terminal, source your venv with `source venv/bin/activate.fish` or whatever works for your shell.
4. Install a working provider version with `pip install pulumi-aws==5.21.1`
5. Run `pulumi up` and deploy all the changes.
6. Run  `pulumi up` a 2nd time, there shouldn't be any changes ✅
7. Up to this point, everything should be fine ✅
8. Install a newer provider version with `pip install pulumi-aws==5.25.0`
9. Run `pulumi up` and now some changes are pending ❌
10. Apply the changes from the step above
11. Revert to an older provider version `pip install pulumi-aws==5.20.0`
12. Run `pulumi up`, only the provider version is to be updated. ✅

### Expected Behavior

Version 5.22.0 and above should behave the same way as 5.21.1 and earlier version, as in, not update/recreate resources when no code changes have occurred.

### Actual Behavior

In version 5.22.0 and above, despite no changes, the stack is being updated and new resources are created/destroyed.

### Output of `pulumi about`

```
CLI          
Version      3.50.2
Go Version   go1.19.4
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.20.0
python  unknown

Host     
OS       debian
Version  11.6
Arch     x86_64

This project is written in python: executable='/home/aureq/work/customers/zendesk/2189/venv/bin/python3' version='3.9.15
'

Current Stack: menfin/zendesk/case-2189

TYPE                                           URN
pulumi:pulumi:Stack                            urn:pulumi:case-2189::zendesk::pulumi:pulumi:Stack::zendesk-case-2189
pulumi:providers:aws                           urn:pulumi:case-2189::zendesk::pulumi:providers:aws::apsoutheast2
aws:ec2/vpc:Vpc                                urn:pulumi:case-2189::zendesk::pulumi:providers:aws$aws:ec2/vpc:Vpc::aureq_case-2189_ap-southeast-2
aws:ec2/subnet:Subnet                          urn:pulumi:case-2189::zendesk::pulumi:providers:aws$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::aureq_0_ap-southeast-2_subnet
aws:ec2/subnet:Subnet                          urn:pulumi:case-2189::zendesk::pulumi:providers:aws$aws:ec2/vpc:Vpc$aws:ec2/subnet:Subnet::aureq_1_ap-southeast-2_subnet
aws:ec2/internetGateway:InternetGateway        urn:pulumi:case-2189::zendesk::pulumi:providers:aws$aws:ec2/vpc:Vpc$aws:ec2/internetGateway:InternetGateway::aureq-case-2189-ap-southeast-2_igw
pulumi:providers:aws                           urn:pulumi:case-2189::zendesk::pulumi:providers:aws::default_5_20_0
aws:ec2/managedPrefixList:ManagedPrefixList    urn:pulumi:case-2189::zendesk::aws:ec2/managedPrefixList:ManagedPrefixList::aureq-case-2189-ap-southeast-2_prefixlist
aws:ec2/vpcEndpoint:VpcEndpoint                urn:pulumi:case-2189::zendesk::aws:ec2/vpcEndpoint:VpcEndpoint::aureq-case-2189-ap-southeast-2_endpoint
aws:ec2/securityGroup:SecurityGroup            urn:pulumi:case-2189::zendesk::pulumi:providers:aws$aws:ec2/vpc:Vpc$aws:ec2/securityGroup:SecurityGroup::aureq-ap-southeast-2-resolver_sg
aws:route53/resolverEndpoint:ResolverEndpoint  urn:pulumi:case-2189::zendesk::pulumi:providers:aws$aws:ec2/vpc:Vpc$aws:route53/resolverEndpoint:ResolverEndpoint::aureq-ap-southeast-2-resolver-inbound
aws:route53/resolverEndpoint:ResolverEndpoint  urn:pulumi:case-2189::zendesk::pulumi:providers:aws$aws:ec2/vpc:Vpc$aws:route53/resolverEndpoint:ResolverEndpoint::aureq-ap-southeast-2-resolver-outbound


Found no pending operations associated with case-2189

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/aureq
User           aureq
Organizations  aureq, team-ce, menfin, menfin-team, demo, pulumi

Dependencies:
NAME        VERSION
pip         22.3.1
pulumi-aws  5.20.0
setuptools  65.6.3
wheel       0.38.4

Pulumi locates its logs in /tmp by default
```

### Additional context

Here is the code I crafted to reproduce the issue.

```python
"""An AWS Python Pulumi program"""

import pulumi
import pulumi_aws as aws

account_name = "aureq"
environment = "dev"
region = "ap-southeast-2"
zona_a = "ap-southeast-2a"
provider = aws.Provider("apsoutheast2", region=region)
vpc_name = "case-2189"

vpc_cidr_block = "10.42.0.0/16"


vpc = aws.ec2.Vpc(
        f"{account_name}_{vpc_name}_{region}",
        cidr_block=vpc_cidr_block,
        enable_dns_hostnames=True,
        opts=pulumi.ResourceOptions(
            parent=provider,
            provider=provider
        ),
    )


subnet_cidr_block_a = "10.42.0.0/24"
public_subnet_a = aws.ec2.Subnet(
    f"{account_name}_0_{region}_subnet",
    vpc_id=vpc.id,
    cidr_block=subnet_cidr_block_a,
    availability_zone=zona_a,
    opts=pulumi.ResourceOptions(
        parent=vpc,
    delete_before_replace=True),
)

subnet_cidr_block_b = "10.42.1.0/24"
public_subnet_b = aws.ec2.Subnet(
    f"{account_name}_1_{region}_subnet",
    vpc_id=vpc.id,
    cidr_block=subnet_cidr_block_b,
    availability_zone=zona_a,
    opts=pulumi.ResourceOptions(
        parent=vpc,
    delete_before_replace=True),
)

igw = aws.ec2.InternetGateway(f"{account_name}-{vpc_name}-{region}_igw",
    vpc_id=vpc.id,
    opts=pulumi.ResourceOptions(
        parent=vpc,
        provider=provider,
        delete_before_replace=True)
)

prefix_list = aws.ec2.ManagedPrefixList(
    f"{account_name}-{vpc_name}-{region}_prefixlist",
    address_family="IPv4",
    max_entries=5,
    entries=[
        aws.ec2.ManagedPrefixListEntryArgs(
            cidr=vpc.cidr_block,
            description="Primary",
        ),
    ],
)

vpc_endpoint = aws.ec2.VpcEndpoint(f"{account_name}-{vpc_name}-{region}_endpoint",
    service_name=f"com.amazonaws.{region}.ec2",
    vpc_id=vpc.id,
    vpc_endpoint_type="Interface",
    private_dns_enabled=True
)

resolver_sg = aws.ec2.SecurityGroup(f"{account_name}-{region}-resolver_sg",
    vpc_id=vpc.id,
    name="resolver_sg",
    ingress=[
        aws.ec2.SecurityGroupIngressArgs(from_port=53, to_port=53, protocol="tcp", prefix_list_ids=[prefix_list.id]),
        aws.ec2.SecurityGroupIngressArgs(from_port=53, to_port=53, protocol="udp", prefix_list_ids=[prefix_list.id])
    ],
    egress=[
        aws.ec2.SecurityGroupEgressArgs( from_port=0, to_port=0, protocol="-1", cidr_blocks=["0.0.0.0/0"])
    ],
    opts=pulumi.ResourceOptions(
        parent=vpc,
        provider=provider,
    ),
)

inbound_resolver = aws.route53.ResolverEndpoint(
    f"{account_name}-{region}-resolver-inbound",
    direction="INBOUND",
    security_group_ids=[
        resolver_sg.id
    ],
    # name="",
    ip_addresses=[
        aws.route53.ResolverEndpointIpAddressArgs(subnet_id=public_subnet_a.id),
        aws.route53.ResolverEndpointIpAddressArgs(subnet_id=public_subnet_b.id),
    ],
    opts=pulumi.ResourceOptions(
        parent=vpc
    ),
)

outbound_resolver = aws.route53.ResolverEndpoint(
    f"{account_name}-{region}-resolver-outbound",
    direction="OUTBOUND",
    security_group_ids=[
        resolver_sg.id
    ],
    # name="",
    ip_addresses=[
        aws.route53.ResolverEndpointIpAddressArgs(subnet_id=public_subnet_a.id),
        aws.route53.ResolverEndpointIpAddressArgs(subnet_id=public_subnet_b.id),
    ],
    opts=pulumi.ResourceOptions(
        parent=vpc
    ),
)

```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment] 2023-02-06 16:58
For users tracking this as pulumi-aws issue: please use [v5.29.1](https://github.com/pulumi/pulumi-aws/releases/tag/v5.29.1) or higher that currently works around the specific problem with ResolverEndpoint, this issue is tracking fixing the root cause to future-proof other resources.

**Comment by t0yv0** [comment] 2023-03-06 17:31
The root cause is now fixed in pulumi-terraform-bridge https://github.com/pulumi/pulumi-terraform-bridge/pull/844 under a feature flag. Feature-flags de-risk the rollout since the change involves Diff method and has a potential of unintentional consequences such as unexpected replace plans on provider upgrades. The tentative plan for gradual rollout is in https://github.com/pulumi/pulumi-terraform-bridge/issues/866

**Closed** 2023-03-06 17:32 UTC
Labels: resolution/fixed, kind/bug
