### ISSUE TITLE
Unable to autoname pf provider

### ISSUE THREAD

**Issue by jaxxstorm** [pulumi/pulumi-terraform-bridge#1265] opened 2023-06-30 16:52 UTC
### What happened?

I am trying to use auto naming for a pf managed provider.

I have the autonaming configured like so: https://github.com/lbrlabs/pulumi-cockroach/blob/autonaming/provider/resources.go#L128

This throws nil pointer dereference. It's very possible I've configured this incorrectly

### Expected Behavior

Autonaming should work

### Steps to reproduce

Check out the autonaming branch of https://github.com/lbrlabs/pulumi-cockroach and run `make`

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2023-07-03 08:08
Autonaming (and compute-defaults) requires a valid `ProviderInfo.P` field. It didn't work at the version of pf and the bridge that you are using. I recommend upgrading to the latest version of the bridge and pf. That will require changing resources.go:

```patch

**Comment by iwahbe** [comment] 2023-07-03 08:10
Duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/1197.

**Closed by iwahbe** 2023-07-03 08:10 UTC
Labels: resolution/duplicate, kind/bug
