### ISSUE TITLE
Name deprecated properties in warnings

### ISSUE THREAD

**Issue by austinbutler** [pulumi/pulumi-terraform-bridge#442] opened 2022-02-02 22:53 UTC
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Creating some `NrqlAlertCondition`s I get the warning `verification warning: Argument is deprecated`, but it doesn't say _what_ argument is deprecated. Through trial-and-error it seems to be `nrql.evaluationOffset`.

### Steps to reproduce

1. Add `newrelic.NrqlAlertCondition` with `nrql: {evaluationOffset: 1}`
2. Run `pulumi up`
3. Notice warning

Expected: If there's a deprecated argument, tell me which one
Actual: I am told there's a deprecated argument, but I have to guess or do trial-and-error

**Comment by jkodroff** [comment] 2022-03-12 03:42
Did some legwork on this:

Here's where the error is coming from in terraform-plugin-sdk: https://github.com/hashicorp/terraform-plugin-sdk/blob/6de4ff033a23058dd0a383df46212c304ff16756/helper/schema/schema.go

And here's where we are error-izing it: https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfshim/diagnostics/error.go

I'm unsure of the level of effort because I would guess that `Diagnostic.AttributePath` would be the HCL attribute, which we'd then have to map to the Pulumi attribute, and I don't know how difficult that mapping is with the available context.

**Comment by austinbutler** [comment] 2022-03-12 08:00
This was with TypeScript and VS Code. It's possible that the IDE was surfacing that to me, and if I see an error like this again I'll definitely check there, but apparently I didn't notice it at the time.

**Comment by austinbutler** [comment] 2022-06-22 00:50
Hit this again today with https://github.com/newrelic/terraform-provider-newrelic/pull/1656. If I hover I do see some indication that the property is deprecated, but no actual warnings or errors from VS Code.

![image](https://user-images.githubusercontent.com/354741/174920054-ddd24df0-20e9-4268-ad42-239986aaf0ae.png)

TBH the bug in https://github.com/pulumi/pulumi-terraform-bridge/issues/77 is preferable to the current status quo. It at least gives me something to start with.

**Comment by joeduffy** [comment] 2023-01-07 23:24
This still seems to be an issue; I just received this:

```
Diagnostics:
  datadog:index:Dashboard (pulumi-metrics):
    warning: urn:pulumi:dev::ddp::datadog:index/dashboard:Dashboard::pulumi-metrics verification warning: Argument is deprecated
```

The problem is the use of `isReadOnly: true` in this program, but you wouldn't know that from the warning text:

```typescript
import * as datadog from "@pulumi/datadog";
import * as pulumi from "@pulumi/pulumi";

const dash = new datadog.Dashboard("pulumi-metrics", {
    title: "Pulumi Metrics",
    layoutType: "ordered",
    isReadOnly: true,
});

export const dashId = dash.id;
```

**Comment by guineveresaenger** [comment] 2023-01-09 21:51
@joeduffy this is likely due to Datadog provider being on an ancient version of the bridge.

Here is Datadog, with the bridge version updated:

```
@guin:terraform-bridge-442🦉 pulumi up
Previewing update (dev)

View Live: https://app.pulumi.com/guinevere/terraform-bridge-442/dev/previews/0fd6028c-417f-439a-a410-7304f800ca5f

     Type                        Name                      Plan       Info
 +   pulumi:pulumi:Stack         terraform-bridge-442-dev  create     
 +   └─ datadog:index:Dashboard  pulumi-metrics            create     1 warning


Diagnostics:
  datadog:index:Dashboard (pulumi-metrics):
    warning: urn:pulumi:dev::terraform-bridge-442::datadog:index/dashboard:Dashboard::pulumi-metrics verification warning: Prefer using `restricted_roles` to define which roles are required to edit the dashboard.

Outputs:
    dashId: output<string>
```

I'm going to close this in favor of pulumi/datadog#210.

**Closed by guineveresaenger** 2023-01-09 21:51 UTC
Labels: resolution/fixed, impact/usability, kind/bug, area/tfshim
