### ISSUE TITLE
`pulumi-auth0` nodejs acceptance tests panic

### ISSUE THREAD

**Issue by aq17** [pulumi/pulumi-terraform-bridge#1138] opened 2023-05-18 20:13 UTC
Failing nodejs logs here https://github.com/pulumi/pulumi-auth0/pull/241

Originally, acceptance tests failed to run due to the test file being named improperly. After fixing it, the test ran and a panic occurred:

 ```
panic: value has no attribute of that name
      goroutine 30 [running]:
      github.com/hashicorp/go-cty/cty.Value.GetAttr({{{0x14be748?, 0xc0000146a8?}}, {0x1120f00?, 0xc00056ad80?}}, {0x12b42cb, 0x8})
      	/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/value_ops.go:700 +0x31b
      github.com/auth0/terraform-provider-auth0/internal/auth0/client.expandClient(0x5d0420?)
      	/home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.47.0/internal/auth0/client/expand.go:20 +0x125
      github.com/auth0/terraform-provider-auth0/internal/auth0/client.createClient({0x14bdbb0, 0xc000390fc0}, 0x111c520?, {0x1133b20?, 0xc000486dd0?})
      	/home/runner/go/pkg/mod/github.com/auth0/terraform-provider-auth0@v0.47.0/internal/auth0/client/resource.go:748 +0x72
      github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc00014b340, {0x14bdb78, 0xc00004a2f8}, 0xd?, {0x1133b20, 0xc000486dd0})
      	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/resource.go:712 +0x12e
      github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc00014b340, {0x14bdb78, 0xc00004a2f8}, 0x0, 0xc00033d280, {0x1133b20, 0xc000486dd0})
      	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/resource.go:842 +0xa85
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0xc000490420?, {0x0?, 0xc00033d280?, 0x0?}}, {0x12b8b6e, 0xc}, {0x0?, 0x0}, {0x14c40d8, 0xc00033d280})
      	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.47.2/pkg/tfshim/sdk-v2/provider.go:100 +0x199
      github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc0000ce500, {0x14bdbe8?, 0xc00056a870?}, 0xc0002841e0)
```

**Comment by t0yv0** [comment] 2023-05-18 21:17
Thanks for reporting @aq17 I think I've reproduced this problem.

Digging in here:

https://github.com/auth0/terraform-provider-auth0/blob/main/internal/auth0/client/expand.go#L14

**Comment by t0yv0** [comment] 2023-05-22 13:47
There's a workaround https://github.com/pulumi/pulumi-auth0/pull/243 deployed so auth0 is unblocked and I don't think this issue is a P0 anymore. Here's what I found during the investigation:

1. the typescript program used to drive the test was essentially not type-correct, a field with a `map[string]any` type (client_metadata in auth0.Client) was populated with a list. Unfortunately due to peculiarities of TypeScript this type-checks. 

2. the data makes it all he way to the provider https://github.com/pulumi/pulumi-terraform-bridge/blob/6a992d9ffc9684ed4a64e87ce06f8b5ff76c84e5/pkg/tfshim/sdk-v2/cty.go#L56-#L56 - unfortunately the current method to "coerce" the data to expected TF type fails quietly with a warning and falls back on to an approximate method; the problem with the approximate method is that it leaves object fields unset instead of setting them to cty.Null values

3. back in client.expandClient auth0 code accesses RawConfig and is ready to handle nulls but panics on empty values.

**Comment by t0yv0** [comment] 2023-05-22 13:51
What we should consider in the bridge is being stricter at the point of coercing the data to TF expected shape. 

We could emit a more visible warning. There is a bit of a usability problem with current methods that don't explain which part of a complicated structure defies expectations, but we could improve on that with some custom "type checking" code that would pin down the error message to the field that's not correctly typed.

Perhaps even more broadly, it could be useful to perform type checking at Pulumi provider level against the provider schema and surface those warnings. While one step removed from the TF ecosystem, a Pulumi level type checking pass is more broadly applicable.

**Comment by VenelinMartinov** [comment] 2024-08-02 09:51
This was fixed in [Type-check incoming values against the Pulumi Package Schema](https://github.com/pulumi/pulumi-terraform-bridge/issues/1328)

The error now explains the type issue:

```
  auth0:index:Client (test):
    warning: Type checking failed:
    warning: Unexpected type at field "clientMetadata":
               expected object type, got [] type
    warning: Type checking is still experimental. If you believe that a warning is incorrect,
    please let us know by creating an issue at https://github.com/pulumi/pulumi-terraform-bridge/issues.
    This will become a hard error in the future.
    error: Preview failed: diffing urn:pulumi:dev::auth0-client::auth0:index/client:Client::test: Resource "auth0_client": recoverCtyValue failed: Cannot reconcile slice [map[foo:bar]] to cty.Map(cty.String)
```

**Closed** 2024-08-02 09:52 UTC
Labels: impact/panic, p1, resolution/fixed, kind/engineering
