### ISSUE TITLE
Unexpected type error with setting skip_metadata_api_check

### ISSUE THREAD

**Issue by DanRepik** [pulumi/pulumi-terraform-bridge#2429] opened 2024-09-19 11:37 UTC
### What happened?

When instantiating a provider and setting the skip_metadata_api_check to the boolean value True the error 'expected boolean type, got "true" of type string' is thrown.

The provider is being instantiated with the following code;

```python
_localstack_provider: Optional[aws.Provider] = None

def localstack_provider() -> aws.Provider:
    global _localstack_provider
    if not _localstack_provider:
        _localstack_provider = aws.Provider(
            "localstack",
            skip_credentials_validation=True, 
            skip_metadata_api_check=True,     # This is not a string
            s3_use_path_style=True,
            region="us-east-2",
            endpoints=[
                aws.ProviderEndpointArgs(
                    s3="http://localhost.localstack.cloud:4566"
                )
            ]
        )
    print(f"localstack_provider: {_localstack_provider}")
    return _localstack_provider
```

I encounter the following error;

```bash
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests/test_fixtures.py:56: in pulumi_stack_up
    up_res = stack.up()
venv/lib/python3.12/site-packages/pulumi/automation/_stack.py:372: in up
    up_result = self._run_pulumi_cmd_sync(args, on_output)
venv/lib/python3.12/site-packages/pulumi/automation/_stack.py:984: in _run_pulumi_cmd_sync
    result = self.workspace.pulumi_command.run(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pulumi.automation._cmd.PulumiCommand object at 0x10a9062a0>
args = ['up', '--yes', '--skip-preview', '--client=127.0.0.1:49894', '--exec-kind', 'auto.inline', ...]
cwd = '/Users/clydedanielrepik/workspace/cloud_foundry', additional_env = {'PULUMI_DEBUG_COMMANDS': 'true'}
on_output = None

    def run(
        self,
        args: List[str],
        cwd: str,
        additional_env: Mapping[str, str],
        on_output: Optional[OnOutput] = None,
    ) -> CommandResult:
        """
        Runs a Pulumi command, returning a CommandResult. If the command fails, a CommandError is raised.
    
        :param args: The arguments to pass to the Pulumi CLI, for example `["stack", "ls"]`.
        :param cwd: The working directory to run the command in.
        :param additional_env: Additional environment variables to set when running the command.
        :param on_output: A callback to invoke when the command outputs data.
        """
    
        # All commands should be run in non-interactive mode.
        # This causes commands to fail rather than prompting for input (and thus hanging indefinitely).
        if "--non-interactive" not in args:
            args.append("--non-interactive")
        env = {**os.environ, **additional_env}
        if os.path.isabs(self.command):
            env = _fixup_path(env, os.path.dirname(self.command))
        cmd = [self.command]
        cmd.extend(args)
    
        stdout_chunks: List[str] = []
    
        with tempfile.TemporaryFile() as stderr_file:
            with subprocess.Popen(
                cmd, stdout=subprocess.PIPE, stderr=stderr_file, cwd=cwd, env=env
            ) as process:
                assert process.stdout is not None
                while True:
                    output = process.stdout.readline().decode(encoding="utf-8")
                    if output == "" and process.poll() is not None:
                        break
                    if output:
                        text = output.rstrip()
                        if on_output:
                            on_output(text)
                        stdout_chunks.append(text)
    
                code = process.returncode
    
            stderr_file.seek(0)
            stderr_contents = stderr_file.read().decode("utf-8")
    
        result = CommandResult(
            stderr=stderr_contents, stdout="\n".join(stdout_chunks), code=code
        )
        if code != 0:
>           raise create_command_error(result)
E           pulumi.automation.errors.CommandError: 
E            code: 255
E            stdout: Updating (local_stack):
E           
E           @ updating.....
E               pulumi:providers:aws localstack  warning: Type checking failed:
E               pulumi:providers:aws localstack  warning: Type checking failed:
E           @ updating......
E               aws:s3:Bucket my-bucket  error: 1 error occurred:
E               pulumi:pulumi:Stack test_project-local_stack
E               aws:s3:Bucket my-bucket **failed** 1 error
E           Diagnostics:
E             pulumi:providers:aws (localstack):
E               warning: Type checking failed:
E           
E                            Unexpected type at field "skipMetadataApiCheck":
E                                expected boolean type, got "true" of type string
E           
E                        Type checking is still experimental. If you believe that a warning is incorrect,
E                        please let us know by creating an issue at https://github.com/pulumi/pulumi-terraform-bridge/issues.
E                        This will become a hard error in the future.
E           
E             aws:s3:Bucket (my-bucket):
E               error: 1 error occurred:
E                       * Retrieving AWS account details: AWS account ID not previously found and failed retrieving via all available methods.
E           
E               See https://www.terraform.io/docs/providers/aws/index.html#skip_requesting_account_id for workaround and implications.
E               Errors: 2 errors occurred:
E                       * retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 403, RequestID: 4349d4fc-f74d-41d2-a2a8-56e163ad43b8, api error InvalidClientTokenId: The security token included in the request is invalid.
E                       * retrieving account information via iam:ListRoles: operation error IAM: ListRoles, https response error StatusCode: 403, RequestID: 18b9fab0-65be-46c7-bd0e-5cf14ef3a084, api error InvalidClientTokenId: The security token included in the request is invalid.
E           
E           Outputs:
E               bucket_arn: "bucket.arn"
E           
E           Resources:
E               2 unchanged
E           
E           Duration: 6s
E           
E            stderr:

venv/lib/python3.12/site-packages/pulumi/automation/_cmd.py:238: CommandError
```

### Example

Run the following pytest;

```python
# tests/test_stack.py

import pulumi
import pulumi_aws as aws
import pulumi.automation as auto
import os
import shutil
from typing import Callable, Dict, Optional, Tuple

# Type alias for the pulumi program function
PulumiProgram = Callable[[], None]

def pulumi_stack_up(stack_name: str, project_name: str, pulumi_program: PulumiProgram) -> Tuple[auto.Stack, Dict[str, auto.OutputValue]]:
    """
    Sets up and runs a Pulumi stack using the specified program.

    Args:
        stack_name (str): The name of the stack.
        project_name (str): The name of the project.
        pulumi_program (PulumiProgram): The inline function defining the Pulumi program.

    Returns:
        Tuple[auto.Stack, Dict[str, auto.OutputValue]]: The deployed Pulumi stack and its outputs.
    """
    
    # Define the local backend for the stack state
    local_backend_path = os.path.join(os.getcwd(), "temp", "pulumi-local-backend")

    # Set the Pulumi backend using an environment variable
    os.environ["PULUMI_BACKEND_URL"] = f"file://{local_backend_path}"

    # Ensure the backend directory exists
    if not os.path.exists(local_backend_path):
        os.makedirs(local_backend_path)

    # Set the stack to use the local filesystem backend
    workspace_opts = auto.LocalWorkspaceOptions(
        work_dir=os.getcwd(),  # Current working directory
        project_settings=auto.ProjectSettings(
            name=project_name,
            runtime="python",
        ),
    )

    # Create or select a Pulumi stack with the local backend
    stack = auto.create_or_select_stack(
        stack_name=stack_name,
        project_name=project_name,
        program=pulumi_program,
        opts=workspace_opts
    )

    # Set configuration options for the stack
    stack.set_config("aws:region", auto.ConfigValue(value="us-west-2"))

    # Deploy the stack and get the outputs
    up_res = stack.up()

    # Return the stack and its outputs
    return stack, up_res.outputs

def pulumi_stack_down(stack):
    # Teardown (destroy the stack after the test)
    stack.destroy()

    # Optionally remove the local backend directory if you want to clean up the state
    local_backend_path = os.path.join(os.getcwd(), "temp", "pulumi-local-backend")
    if os.path.exists(local_backend_path):
        shutil.rmtree(local_backend_path)

_localstack_provider: Optional[aws.Provider] = None

def localstack_provider() -> aws.Provider:
    global _localstack_provider
    if not _localstack_provider:
        _localstack_provider = aws.Provider(
            "localstack",
            skip_credentials_validation=True,  # Ensure AWS credential validation is skipped
            skip_metadata_api_check=True,      # Ensure AWS metadata API validation is skipped
            s3_use_path_style=True,
            region="us-east-2",
            endpoints=[
                aws.ProviderEndpointArgs(
                    s3="http://localhost.localstack.cloud:4566"
                )
            ]
        )
    print(f"localstack_provider: {_localstack_provider}")
    return _localstack_provider

# Example of a test using the common function
def test_bucket_creation() -> None:
    """
    Test function to create an S3 bucket using Pulumi and LocalStack.
    """

    # Define the Pulumi program for the test
    def pulumi_program() -> None:
        # Create an S3 bucket using the LocalStack provider
        bucket = aws.s3.Bucket(
            "my-bucket",
            versioning={"enabled": True},
            opts=pulumi.ResourceOptions(provider=localstack_provider()),
        )

        # Export the bucket's ARN (Amazon Resource Name)
        # pulumi.export("bucket_arn", bucket.arn)
        pulumi.export("bucket_arn", "bucket.arn")

    stack = None
    try:
        # Call the common function to deploy the stack
        stack, outputs = pulumi_stack_up("local_stack", "test_project", pulumi_program)

        # Assert that the bucket ARN was created and is part of the outputs
        assert "bucket_arn" in outputs
        assert outputs["bucket_arn"].value.startswith("arn:aws:s3")
        print(f"S3 Bucket ARN: {outputs['bucket_arn'].value}")
    finally:
        if stack:
            pulumi_stack_down(stack)
```

### Output of `pulumi about`

(venv) clydedanielrepik@Dans-MacBook-Pro cloud_foundry % pulumi about
CLI          
Version      3.133.0
Go Version   go1.23.1
Go Compiler  gc

Plugins
KIND      NAME        VERSION
resource  automation  0.1.0
resource  aws         6.52.0
language  python      3.133.0

Host     
OS       darwin
Version  14.6.1
Arch     x86_64

This project is written in python: executable='/Users/clydedanielrepik/workspace/cloud_foundry/venv/bin/python3' version='3.12.5'

Backend        
Name           Dans-MacBook-Pro.local
URL            file://~
User           clydedanielrepik
Organizations  
Token type     personal

Dependencies:
NAME                   VERSION
build                  1.2.2
localstack-playground  0.1.5
pip                    24.2
pulumi-automation      0.1.0
pulumi_aws             6.52.0
pytest                 8.3.3
twine                  5.1.1

Pulumi locates its logs in /var/folders/h3/1m7s7c3s5sv20mctfrb0b57m0000gp/T/ by default
warning: Failed to get information about the current stack: No current stack
(venv) clydedanielrepik@Dans-MacBook-Pro cloud_foundry % 

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2024-09-20 08:31
Hi @DanRepik. Thanks for opening an issue. I'm sorry your hitting this. It looks like a duplicate of https://github.com/pulumi/pulumi-terraform-bridge/issues/2339.

**Closed by iwahbe** 2024-09-20 08:31 UTC
Labels: resolution/duplicate, kind/bug
