### ISSUE TITLE
Confusing provider configuration error message

### ISSUE THREAD

**Issue by stack72** [pulumi/pulumi-terraform-bridge#343] opened 2021-04-21 15:20 UTC
When setting the following for AzureAD:

```
azuread:clientId: ******
azuread:clientSecret:
  secure: ******
azuread:subscriptionId: ******
azuread:tenantId: ******
```

we get the error message:

```
Diagnostics:
  azuread:index:Application (aks):
    error: could not validate provider configuration: 1 error occurred:
        * Invalid or unknown key
```

This is because subscriptionId is not a valid configuration value but the error message doesn't tell us that

**Comment by rafaribe** [comment] 2021-06-18 14:35
If you remove the `azuread:subscriptionId` then it reports that it is missing, so what is the workarround?

**Comment by t0yv0** [comment] 2023-05-26 02:48
This looks like a duplicate of #906 ; with https://github.com/pulumi/pulumi-terraform-bridge/pull/1153 released in https://github.com/pulumi/pulumi-terraform-bridge/releases/tag/v3.47.4 the error message should be more informative. Note that for this to work with azuread it needs to upgrade to the latest version, which will happen in the next release.

**Closed** 2023-05-26 02:48 UTC
Labels: resolution/duplicate, impact/usability, kind/bug
