### ISSUE TITLE
bug: `vultr:apiKey` is not a valid configuration key for the vultr provider

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-terraform-bridge#2582] opened 2024-11-04 09:59 UTC
### What happened?

This appears to be a regression between `2.20.1` and `2.21.1`.

It previously worked to set a config key `vultr:apiKey`, including as a secret, to set the vultr configuration. But some change has made this break between these versions.

Output of `pulumi up`:

```bash
Diagnostics:
  pulumi:providers:vultr (default_2_21_1_github_/api.github.com/dirien/pulumi-vultr):
    error: pulumi:providers:vultr resource 'default_2_21_1_github_/api.github.com/dirien/pulumi-vultr' has a problem: `vultr:apiKey` is not a valid configuration key for the vultr provider. If the referenced key is not intended for the provider, please choose a different namespace from `vultr:`.
```

### Example

index.ts

```typescript
import * as vultr from "@ediri/vultr";

let vke = new vultr.Kubernetes("vke", {
    region: "fra",
    version: "v1.25.4+1",
    label: "pulumi-vultr",
    nodePools: {
        nodeQuantity: 1,
        plan: "vc2-2c-4gb",
        label: "pulumi-vultr-nodepool",
    },
})

export const kubeconfig = vke.kubeConfig;
````

package.json

```json
{
  "name": "vultr-ts",
  "main": "index.ts",
  "devDependencies": {
    "@types/node": "^18"
  },
  "dependencies": {
    "@pulumi/pulumi": "^3.0.0",
    "@ediri/vultr": "2.21.1"
  }
}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2024-11-04 12:22
I'm marking as P1, since it looks like a regression. If we are not able to demonstrate a regression, we can remove the label.

**Comment by guineveresaenger** [comment] 2024-11-04 23:09
I'll take a look to pinpoint as soon as I can.

**Comment by guineveresaenger** [comment] 2024-11-06 00:56
Update: 
I've confirmed this is still an issue, even when this provider gets updated to the latest bridge. 
The error message commit (PR #1663), however, is not the cause.

The cause being that vultr's `provider.configType.AttributeTypes` is an empty map, so that the [attribute type lookup](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/pf/tfbridge/provider_checkconfig.go#L211) fails.

The issue goes away when `SkipValidateProviderConfigForPluginFramework` is set to `true` on the provider; however that feels like incorrect usage of skipping config validation, as per #1448 this setting is meant to avoid a performance slowdown - not skip validation altogether. In fact, this particular field is currently _only_ being used for AWS so I expect this is another red herring and we do not, in fact, want to skip this validation.

It's a little difficult to bisect which bridge version introduces this behavior, since this provider's bridge version is not being regularly updated.

**Comment by guineveresaenger** [comment] 2024-11-06 17:14
@iwahbe I'm not sure - it seems more like that there are no config types for the PF version - the `configType.AttributeTypes` is an empty map.

In `pkg/pf/internal/configencoding/provider.go`, `CheckConfigWithContext` returns the following properties:
```
props=resource.PropertyMap{
           "apiKey": {
               V:  "12345",
           },
           "version": {
               V:  "2.21.1",
           },
       }
```
which is Good and Correct
but 

```
failures=[]plugin.CheckFailure{
           {Property:"", Reason:"`vultr:apiKey` is not a valid configuration key for the vultr provider. If the referenced key is not intended for the provider, please choose a different namespace from `vultr:`."},
       }
```
because the attribute type lookup fails.

**Comment by guineveresaenger** [comment] 2024-11-07 23:24
@iwahbe after staring at the stacktrace, I ran this with logging and it looks like you are correct.

```
I1107 14:28:11.742390   68983 muxer.go:158] [muxer] CheckConfig results do not agree on the 'apiKey' property:
        server 0: {"4dabf18193072939515e22adb298388d":"1b47061264138c4ac30d75fd1eb44270", "value":"12345"}
        server 1: "12345"
    Picking the server 0 response
```

But when I set the `apiKey` property to not secret in the provider schema, this particular line is not logged... but the error still persists.

Looks like a red herring perhaps.

Logs without secret-ifying `apiKey`:
```
Diagnostics:
  pulumi:providers:vultr (default_2_21_1_github_/api.github.com/dirien/pulumi-vultr):
    error: pulumi:providers:vultr resource 'default_2_21_1_github_/api.github.com/dirien/pulumi-vultr' has a problem: `vultr:apiKey` is not a valid configuration key for the vultr provider. If the referenced key is not intended for the provider, please choose a different namespace from `vultr:`.
[...]
    warning: using pulumi-resource-vultr from $PATH at /Users/guin/go/src/github.com/dirien/pulumi-vultr/bin/pulumi-resource-vultr
    warning: using pulumi-resource-vultr from $PATH at /Users/guin/go/src/github.com/dirien/pulumi-vultr/bin/pulumi-resource-vultr

    I1107 15:02:50.622116   72041 rpc.go:292] Unmarshaling property for RPC[inputs]: apiKey={12345}
    I1107 15:02:50.622195   72041 rpc.go:292] Unmarshaling property for RPC[inputs]: version={2.21.1}
    I1107 15:02:50.623253   72041 provider.go:524] tf.Provider[vultr].CheckConfig(urn:pulumi:dev::bridge-2582::pulumi:providers:vultr::default_2_21_1_github_/api.github.com/dirien/pulumi-vultr) executing
    I1107 15:02:50.623325   72041 rpc.go:292] Unmarshaling property for RPC[config]: apiKey={12345}
    I1107 15:02:50.623329   72041 rpc.go:292] Unmarshaling property for RPC[config]: version={2.21.1}
    I1107 15:02:50.623407   72041 schema.go:658] Created Terraform input: api_key = 12345
    I1107 15:02:50.623442   72041 schema.go:859] Created Terraform input: rate_limit = 500 (from Pulumi schema)
    I1107 15:02:50.623462   72041 schema.go:859] Created Terraform input: retry_limit = 3 (from Pulumi schema)
    I1107 15:02:50.623465   72041 schema.go:668] Terraform input api_key = "12345"
    I1107 15:02:50.623467   72041 schema.go:668] Terraform input rate_limit = 500
    I1107 15:02:50.623469   72041 schema.go:668] Terraform input retry_limit = 3
    I1107 15:02:50.623470   72041 schema.go:668] Terraform input __defaults = []interface {}{"rateLimit", "retryLimit"}
    I1107 15:02:50.623596   72041 rpc.go:77] Marshaling property for RPC[config]: apiKey={12345}
    I1107 15:02:50.623600   72041 rpc.go:77] Marshaling property for RPC[config]: version={2.21.1}
    I1107 15:02:50.625274   72041 rpc.go:77] Marshaling property for RPC[config]: apiKey={12345}
    I1107 15:02:50.625280   72041 rpc.go:77] Marshaling property for RPC[config]: version={2.21.1}

**Comment by guineveresaenger** [comment] 2024-11-08 18:34
Update:

As @VenelinMartinov noticed today, the upstream terraform provider for pulumi-vultr is [not actually using the Terraform Plugin Framework at all.](https://github.com/vultr/terraform-provider-vultr/blob/master/go.mod) This results, very correctly, in the plugin framework validation step not being able to see any defined config types on the (nonexistent) Plugin Framework provider.

The Pulumi provider, however, [adds the Plugin Framework as a shim package](https://github.com/dirien/pulumi-vultr/blob/main/provider/shim/shim.go#L6), causing this discrepancy.

To resolve this is to revert the changes made in or around https://github.com/dirien/pulumi-vultr/pull/337 cc @dirien .

This is not a bridge bug.

**Closed by guineveresaenger** 2024-11-08 18:34 UTC
Labels: p1, kind/bug, resolution/by-design
