### ISSUE TITLE
Some property descriptions map to the wrong property

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-bridge#1789] opened 2024-03-26 09:27 UTC
### What happened?

When we generate docs, we scrape upstream property descriptions and apply them to the corresponding pulumi property. We don't always get the mapping right.

Sometimes, especially when there are multiple properties with the same name (but different nesting), we match the wrong description with a property.

### Example

This issue motivated me to open a tracking issue in the bridge, but I have seen this happen multiple times.

- https://github.com/pulumi/pulumi-cloudflare/issues/661

### Output of `pulumi about`

NA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by guineveresaenger** [comment] 2024-03-29 18:06
We do mismatch them [intentionally, it seems](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/generate.go#L1849). Removing that code block (based on #1798 changes) results in correct description for `module`. 

A contributing factor may be that the Cloudflare provider [does not have a docs structure that we expect when grouping sections](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/docs.go#L722) - there is [only a section called Schema](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_policy#schema), so _most_ of our documentation gets read into `entityDocs.Attributes` rather than `entityDocs.Arguments`, resulting in more parsing clashes.

I'm going to experiment with removing the abovementioned section. A cursory glance at the Cloudflare schema built with this change seems to improve accuracy (but remove some documentation and causes a fair bit of churn in Description fields).

Note some [interesting context on a previous improvements iteration with a Cloudflare example](https://github.com/pulumi/pulumi-cloudflare/pull/493/files#r1337274428)

**Comment by guineveresaenger** [comment] 2024-03-30 00:27
Update:

So I root caused the final(?) bug that was uncovered by removing the [description section matching hack](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/generate.go#L1849).

Basically what happened was that the Arguments had double-nested docs paths keys of the following format:
`nestedSchemaName.TypeList.TypeName` -> `exclude.azure.id`
but when creating object resources we only consider the current docs path and its key, which would be
`TypeList.YppeName - `azure.id`.

So when getting docs descriptions, the Argument key present was `exclude.azure.id` but we only look for the keys "azure.id" and "id". The latter then falls through to Attribute map, which has an "id" key and thus the nested ids read "The ID of the resource", which is actually a _top-level_ description field on CloudflareAccessPolicy.
A hardcoded `exclude` as an extra prefix makes all of the buggy behavior goes away for that particular resource. 
To solve, we must devise a way to look up the parent resource and keep it in the docsPath, possibly recursively.

I believe applying both these changes will result in much more accurate documentation for duplicate-leaf name property fields!

See the [upstream docs page for Access Policy](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_policy#schema)

See ours [displaying the first bug](https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/access_policy#schema)

All of this must be tested against larger providers as well.

**Comment by mikhailshilkov** [comment] 2024-04-01 08:39
Is this another case of the same issue? https://github.com/pulumi/pulumi-cloudflare/issues/700

Is cloudflare somehow worse at this compared to other providers?

**Comment by guineveresaenger** [comment] 2024-04-01 16:09
I believe [pulumi/pulumi-cloudflare#700](https://github.com/pulumi/pulumi-cloudflare/issues/700) is another instance of this yes.

I don't believe Cloudflare is categorically worse at this. It is my suspicion that _all_ providers that have a "Schema" --> "Required/Optional/Read-only/Nested Schema for X" structure share similar issues, in the situation where sibling Nested Schema fields share the same name at the leaf end of the token/docs path (`name` and `id` are particularly common). The thing that at first glance offsets Cloudflare here is that Cloudflare has a _lot_ of detailed Nested Schemas of this kind.

**Comment by guineveresaenger** [comment] 2024-04-03 00:26
Update:

- The mismatched mapping in property descriptions is fixed by removing [this code](https://github.com/pulumi/pulumi-terraform-bridge/blob/master/pkg/tfgen/generate.go#L1849). I am fairly confident that this results in _correct_ docs, but it also removes a large amount of docs that were found and "matched" by this code.
- This uncovered _multiple_ bugs in the docs generation so far:
   - Arguments with multi-layer nesting in the Arguments section were not matched correctly; the fix for this is to uncover the entire ancestral docs path.
   - Several Description fields were read from the TF schema but with the above changes are now read from the Docs
   - Parsing the docs does not always generate the correct docs path argument key in the entity docs; for instance [https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/resources/page_rule#user] this resource has nested resource fields, but entityDocs listed them on the same level as `user`, resulting in empty docs.

   
[Experiments branch so far](https://github.com/pulumi/pulumi-terraform-bridge/tree/guin/docs-mismatching-experiments)
   
We lose a lot of docs descriptions with the above approach. We also gain some, and they are more accurate.

For Cloudflare, this tradeoff makes sense, and we could close pulumi/pulumi-cloudflare#700 and pulumi/pulumi-cloudflare#661.
However - for AWS, these changes lose us thousands of docs, a lot of which are correct.
```
git diff master --stat provider/cmd/
 provider/cmd/pulumi-resource-aws/schema.json | 8749 +++++++++++++++++++++++++++++++++--------------------------------------------------------------
 1 file changed, 2990 insertions(+), 5759 deletions(-)
 ```

Suggested path forward: Spend time making the docs parsing a bit more robust with an eye towards AWS, i.e. make sure docs paths are closer to the schema path so we do not have to match path leaves that aren't part of the same resource and can safely delete the code causing mismatching descriptions.

**Comment by iwahbe** [comment] 2024-04-03 13:21
> Suggested path forward: Spend time making the docs parsing a bit more robust with an eye towards AWS, i.e. make sure docs paths are closer to the schema path so we do not have to match path leaves that aren't part of the same resource and can safely delete the code causing mismatching descriptions.

Sounds good to me! Thanks for the update.

**Comment by guineveresaenger** [comment] 2024-04-15 16:02
Another update.

I have successfully added extra parsing to the docs discovery process that at least in the case of a single AWS demo resource renders more correct documentation and allows for removal of the hack described above, which would fix this issue for Cloudflare.

I'll need more verification to determine if this is a valid approach across the board but it's a start.

**Comment by guineveresaenger** [comment] 2024-04-15 17:31
Filed https://github.com/pulumi/pulumi-terraform-bridge/issues/1876  and https://github.com/pulumi/pulumi-terraform-bridge/issues/1875 to capture some of the uncovered behavior.

**Comment by guineveresaenger** [comment] 2024-04-15 23:27
Alright. I am pretty close! AWS docs are overall similarly populated, and in multiple cases more correct. I've addressed both bridge issues I filed today in https://github.com/pulumi/pulumi-terraform-bridge/tree/guin/docs-mismatching-experiments. 

I did discover a few types that share names being mismatched still, and I'm going to take another look at the `getNestedDescriptionFromParsedDocs` logic. I believe the issue is that the docsPath is not comprehensive.

**Comment by guineveresaenger** [comment] 2024-04-17 01:15
Cloudflare's two docs bugs are fixed with my experimental branch of the bridge. In fact, a schema diff brings us many more descriptions, and many fixes where descriptions were misaligned.

AWS is still losing a lot of descriptions:
` 1 file changed, 2903 insertions(+), 5299 deletions(-)`

I have reasonable confidence:

1. The descriptions that exist are correct, and aligned with the correct resource fields! 🎉 
2. I can add more refinement to the docs parsing to ensure we get more descriptions for AWS.

**Comment by guineveresaenger** [comment] 2024-04-17 15:41
Yes, I went through the diff to get some general trends. 
- Some of the missing docs should in fact be missing; they do not exist upstream
- Others exist upstream and are missing because they had previously been approximated, but the enw logic doesn't know how to find them yet
- There's always the possibility that some are missing because of a new bug.

**Closed** 2024-04-22 17:28 UTC
Labels: kind/bug
