### ISSUE TITLE
Error on creating azure.storage.ManagementPolicy

### ISSUE THREAD

**Issue by tmeckel** [pulumi/pulumi-terraform-bridge#720] opened 2022-12-22 11:19 UTC
### What happened?

Trying to deploy a `azure.storage.ManagementPolicy` resource. If not all *optional* parameters for actions are set explicitly, an error is thrown stating that `-1` is not in the range of acceptable values.

![image](https://user-images.githubusercontent.com/14177833/209122469-13e46cb8-3e23-4e72-bdcd-07443ced68ee.png)

### Steps to reproduce

1. Create Storage Account
2. Create Storage Account Container `azure.storage.Container`
3. Create Storage Account Management Policy as described in the current documentation https://www.pulumi.com/registry/packages/azure/api-docs/storage/managementpolicy/ and not set all possible action values.

```typescript
  const exampleManagementPolicy = new azure.storage.ManagementPolicy("managementPolicyRobotFramework", {
    storageAccountId: args.storageAccount.id,
    rules: [
      {
        name: "robot-framework",
        enabled: true,
        filters: {
          prefixMatches: [
            containerName,
          ],
          blobTypes: [
            "blockBlob",
          ],
        },
        actions: {
          baseBlob: {
            deleteAfterDaysSinceModificationGreaterThan: 30,
            // deleteAfterDaysSinceCreationGreaterThan: 0,
            // deleteAfterDaysSinceLastAccessTimeGreaterThan: 0,
            // tierToArchiveAfterDaysSinceCreationGreaterThan: 0,
            // tierToArchiveAfterDaysSinceLastAccessTimeGreaterThan: 0,
            // tierToArchiveAfterDaysSinceLastTierChangeGreaterThan: 0,
            // tierToArchiveAfterDaysSinceModificationGreaterThan: 0,
            // tierToCoolAfterDaysSinceCreationGreaterThan: 0,
            // tierToCoolAfterDaysSinceLastAccessTimeGreaterThan: 0,
            // tierToCoolAfterDaysSinceModificationGreaterThan: 0,
          },
          snapshot: {
            deleteAfterDaysSinceCreationGreaterThan: 30,
            // changeTierToArchiveAfterDaysSinceCreation: 0,
            // changeTierToCoolAfterDaysSinceCreation: 0,
            // tierToArchiveAfterDaysSinceLastTierChangeGreaterThan: 0,
          },
          version: {
            deleteAfterDaysSinceCreation: 30,
            // changeTierToArchiveAfterDaysSinceCreation: 0,
            // changeTierToCoolAfterDaysSinceCreation: 0,
            // tierToArchiveAfterDaysSinceLastTierChangeGreaterThan: 0,
          }
        }
      }
    ]
  })
```

### Expected Behavior

Storage Account Management Policy  got created by Pulumi

### Actual Behavior

Error thrown while performing `pulumi preview`

![image](https://user-images.githubusercontent.com/14177833/209122469-13e46cb8-3e23-4e72-bdcd-07443ced68ee.png)

### Output of `pulumi about`

`pulumi about` with sensitive information removed.

```
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME     VERSION
azure    5.27.0
azuread  5.32.0
nodejs   unknown
random   4.8.2

Host     
OS       debian
Version  11.4
Arch     x86_64

This project is written in nodejs: executable='/usr/local/bin/node' version='v16.16.0'

Dependencies:
NAME             VERSION
@types/node      12.20.55
md5-file         5.0.0
@pulumi/azure    5.27.0
@pulumi/azuread  5.32.0
@pulumi/pulumi   3.38.0
@pulumi/random   4.8.2
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by tmeckel** [comment] 2023-01-17 16:26
@danielrbradley When I look again at my proposal I'd switch from a `ApplyDefaults` which requires a `true` value to `DontApplyDefaults` because the default for a `boolean`  in Go is `false`. I think this will (a) reduce the risk of regressions and (b) will limit the blast radius for code changes.

**Comment by t0yv0** [comment] 2023-01-30 23:57
Thank you for a detailed issue! 

I have a fix for consideration that works around this class of error by ignoring defaults that do not validate:

 https://github.com/pulumi/pulumi-terraform-bridge/pull/768

I have confirmed it fixes the problem as stated when applied to pulumi/pulumi-azure.

The other suggestions are interesting but given a large number of providers that depend on the bridge that may rely on the current behavior currently there is a strong preference for tactical fixes.

**Comment by tmeckel** [comment] 2023-03-07 11:35
@t0yv0 Finally I had some time to come back to this and run some tests. Seems that the pr #720 didn't fix the issue completely.

Th following Typescript code, creates a property with a default value. Is this an overlooked edge case?

```typescript
const managementPolicy = new azure.storage.ManagementPolicy("managementPolicyRobotFramework", {
    storageAccountId: args.storageAccount.id,
    rules: [
      {
        name: "robot-framework",
        enabled: true,
        filters: {
          prefixMatches: [
            containerName,
          ],
          blobTypes: [
            "blockBlob",
          ],
        },
        actions: {
          baseBlob: {
            deleteAfterDaysSinceModificationGreaterThan:
              args.expirationSettings?.blobDeleteAfterDays
              ?? 30,
          },
          snapshot: {
            deleteAfterDaysSinceCreationGreaterThan:
              args.expirationSettings?.snapshotDeleteAfterDays
              ?? args.expirationSettings?.blobDeleteAfterDays
              ?? 30,
          },
          version: {
            deleteAfterDaysSinceCreation:
              args.expirationSettings?.versionDelereAfterDays
              ?? args.expirationSettings?.blobDeleteAfterDays
              ?? 30,
          }
        }
      }
    ]
  })
```

![image](https://user-images.githubusercontent.com/14177833/223410889-39b14155-9e5a-4b48-8baa-74fbb30799c8.png)

**Comment by t0yv0** [comment] 2023-03-07 19:29
Well, I can sort of reproduce the -1 appearing but I'm wondering if this is a problem. Here's a program I'm using.

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as azure from "@pulumi/azure";

const containerName = "my-container";

const exampleResourceGroup = new azure.core.ResourceGroup("exampleResourceGroup", {location: "West Europe"});

const exampleAccount = new azure.storage.Account("exampleaccount", {
    resourceGroupName: exampleResourceGroup.name,
    location: exampleResourceGroup.location,
    accountTier: "Standard",
    accountReplicationType: "GRS",
    tags: {
        environment: "staging",
    },
});

export const managementPolicy = new azure.storage.ManagementPolicy("managementPolicyRobotFramework", {
    storageAccountId: exampleAccount.id,
    rules: [
      {
        name: "robot-framework",
        enabled: true,
        filters: {
          prefixMatches: [
            containerName,
          ],
          blobTypes: [
            "blockBlob",
          ],
        },
        actions: {
          baseBlob: {
            deleteAfterDaysSinceModificationGreaterThan: 30
          },
          snapshot: {
            deleteAfterDaysSinceCreationGreaterThan: 30,
          },
          version: {
            deleteAfterDaysSinceCreation: 30
          }
        }
      }
    ]
  })

```

 pulumi up succeeds.

There are some -1s showing indeed.

The first one shows up in Check because the upstream spec for it does not specify ValidateFunc range for some reason, so tierToCoolAfterDaysSinceLastAccessTimeGreaterThan=-1 is a valid value as far as the provider cares.

```
{
  "method": "/pulumirpc.ResourceProvider/Check",
  "request": {
    "urn": "urn:pulumi:dev::repro-pulumi-terraform-bridge-720::azure:storage/managementPolicy:ManagementPolicy::managementPolicyRobotFramework",
    "olds": {},
    "news": {
      "rules": [
        {
          "actions": {
            "baseBlob": {
              "deleteAfterDaysSinceModificationGreaterThan": 30
            },
            "snapshot": {
              "deleteAfterDaysSinceCreationGreaterThan": 30
            },
            "version": {
              "deleteAfterDaysSinceCreation": 30
            }
          },
          "enabled": true,
          "filters": {
            "blobTypes": [
              "blockBlob"
            ],
            "prefixMatches": [
              "my-container"
            ]
          },
          "name": "robot-framework"
        }
      ],
      "storageAccountId": "04da6b54-80e4-46f7-96ec-b56ff0331ba9"
    },
    "randomSeed": "xOM+qoIZSxQzKzUdSAeu78Cj1UktgyhchureF37Pxx0="
  },
  "response": {
    "inputs": {
      "__defaults": [],
      "rules": [
        {
          "__defaults": [],
          "actions": {
            "__defaults": [],
            "baseBlob": {
              "__defaults": [
                "tierToCoolAfterDaysSinceLastAccessTimeGreaterThan"
              ],
              "deleteAfterDaysSinceModificationGreaterThan": 30,
              "tierToCoolAfterDaysSinceLastAccessTimeGreaterThan": -1
            },
            "snapshot": {
              "__defaults": [],
              "deleteAfterDaysSinceCreationGreaterThan": 30
            },
            "version": {
              "__defaults": [],
              "deleteAfterDaysSinceCreation": 30
            }
          },
          "enabled": true,
          "filters": {
            "__defaults": [],
            "blobTypes": [
              "blockBlob"
            ],
            "prefixMatches": [
              "my-container"
            ]
          },
          "name": "robot-framework"
        }
      ],
      "storageAccountId": "04da6b54-80e4-46f7-96ec-b56ff0331ba9"
    }
  },
  "metadata": {
    "kind": "resource",
    "mode": "client",
    "name": "azure"
  }
}
```

Things get a lot more interesting in Create preview.

```
{
  "method": "/pulumirpc.ResourceProvider/Create",
  "request": {
    "urn": "urn:pulumi:dev::repro-pulumi-terraform-bridge-720::azure:storage/managementPolicy:ManagementPolicy::managementPolicyRobotFramework",
    "properties": {
      "__defaults": [],
      "rules": [
        {
          "__defaults": [],
          "actions": {
            "__defaults": [],
            "baseBlob": {
              "__defaults": [
                "tierToCoolAfterDaysSinceLastAccessTimeGreaterThan"
              ],
              "deleteAfterDaysSinceModificationGreaterThan": 30,
              "tierToCoolAfterDaysSinceLastAccessTimeGreaterThan": -1
            },
            "snapshot": {
              "__defaults": [],
              "deleteAfterDaysSinceCreationGreaterThan": 30
            },
            "version": {
              "__defaults": [],
              "deleteAfterDaysSinceCreation": 30
            }
          },
          "enabled": true,
          "filters": {
            "__defaults": [],
            "blobTypes": [
              "blockBlob"
            ],
            "prefixMatches": [
              "my-container"
            ]
          },
          "name": "robot-framework"
        }
      ],
      "storageAccountId": "04da6b54-80e4-46f7-96ec-b56ff0331ba9"
    },
    "preview": true
  },
  "response": {
    "properties": {
      "id": "",
      "rules": [
        {
          "actions": {
            "baseBlob": {
              "deleteAfterDaysSinceCreationGreaterThan": -1,
              "deleteAfterDaysSinceLastAccessTimeGreaterThan": -1,
              "deleteAfterDaysSinceModificationGreaterThan": 30,
              "tierToArchiveAfterDaysSinceCreationGreaterThan": -1,
              "tierToArchiveAfterDaysSinceLastAccessTimeGreaterThan": -1,
              "tierToArchiveAfterDaysSinceLastTierChangeGreaterThan": -1,
              "tierToArchiveAfterDaysSinceModificationGreaterThan": -1,
              "tierToCoolAfterDaysSinceCreationGreaterThan": -1,
              "tierToCoolAfterDaysSinceLastAccessTimeGreaterThan": -1,
              "tierToCoolAfterDaysSinceModificationGreaterThan": -1
            },
            "snapshot": {
              "changeTierToArchiveAfterDaysSinceCreation": -1,
              "changeTierToCoolAfterDaysSinceCreation": -1,
              "deleteAfterDaysSinceCreationGreaterThan": 30,
              "tierToArchiveAfterDaysSinceLastTierChangeGreaterThan": -1
            },
            "version": {
              "changeTierToArchiveAfterDaysSinceCreation": -1,
              "changeTierToCoolAfterDaysSinceCreation": -1,
              "deleteAfterDaysSinceCreation": 30,
              "tierToArchiveAfterDaysSinceLastTierChangeGreaterThan": -1
            }
          },
          "enabled": true,
          "filters": {
            "blobTypes": [
              "blockBlob"
            ],
            "matchBlobIndexTags": [],
            "prefixMatches": [
              "my-container"
            ]
          },
          "name": "robot-framework"
        }
      ]
    }
  },
  "metadata": {
    "kind": "resource",
    "mode": "client",
    "name": "azure"
  }
}
```

For things like changeTierToArchiveAfterDaysSinceCreation under version -1 seems illegal. But that somehow works out now.

**Comment by tmeckel** [comment] 2023-03-07 19:32
@t0yv0 I'll try to deploy the mentioned changes from my last comment. I'll let you know the outcome. Many thanks for the thorough analysis ❤️

**Comment by t0yv0** [comment] 2023-03-07 19:41
I have also this pinned in a unit test now in https://github.com/pulumi/pulumi-terraform-bridge/pull/874  which makes it easier to experiment.

Unfortunately poking around it I'm still bit confused of where a fix should go, if anywhere. At first I thought that the issue is that the previous fix didn't go "deep enough" and some bridge code got exposed to pre-defaults-correction schema. But it looks like that's not sufficient. Something around here:

```
func (s v2InstanceState) Object(sch shim.SchemaMap) (map[string]interface{}, error) {
```

is calling into schema.FieldReader that's not seeing corrections.

Moreover, just playing with correcting the schema by hand, I was not able to coax it to just skip the attributes like "tierToArchiveAfterDaysSinceLastAccessTimeGreaterThan": -1 for some reason.. If not given default values -1, it populates them with 0, even though they're optional. 0 is probably not what we want at all since provider may take action as if it's a constraint 0 (not missing).

**Comment by t0yv0** [comment] 2023-03-07 19:43
Please let me know if there's a remaining issue blocking your work and we'll prioritized accordingly; if it's just an annoying quirk then we might need to park for now; when coming back to it it would be great to cross-compare with how TF CLI handles this program and figure out these details.

**Comment by tmeckel** [comment] 2023-03-08 21:10
@t0yv0 Sorry for the delay. I applied the change using `pulumi up -r`.

**Preview**

![image](https://user-images.githubusercontent.com/14177833/223848469-d706a7f8-b59a-4b01-86c8-4a408212aa3d.png)

**Output**

![image](https://user-images.githubusercontent.com/14177833/223848711-621ef0fd-6772-4535-9c1d-fc6df10541a8.png)

Issue is that everywhere in the output you'll find the illegal default value (-1). 

Much more problematic is the fact that I know have the following error, while staring an additional `pulumi up -r`. Either this is an issue with the default values, or the used provider version 5.36.0 has a bug here. Or simply the error is completely unrelated and the stack got corrupted. Doesn't have the time yet for further investigations. I'll getting back on this tomorrow for sure.

![image](https://user-images.githubusercontent.com/14177833/223849403-1aac7608-ed26-4d69-aaf0-72554d938313.png)

**Comment by t0yv0** [comment] 2023-03-08 21:41
Him, interesting, it sounds to me the "ID was missing the `webHooks` element` in RegistryWebhook is possibly another issue unrelated to -1. None of the code in this issue so far mentions RegistryWebhook, perhaps if you manage to isolate a bit of code with RegistryWebhook that has this weird behavior that'd be super helpful. I searched pulumi-azure tracker for RegistryWebhook issues but didn't find anything yet.

**Comment by tmeckel** [comment] 2023-03-29 13:30
@t0yv0 Found the issue. Inside the Pulumi stack the resource id is lower case on the `webHooks` element:

`/subscriptions/e5116c25-7bc9-4e96-9c3e-88257f68db7c/resourceGroups/RG-WKB-Test/providers/Microsoft.ContainerRegistry/registries/acr4189bf944305c36f/webhooks/b1ec43f3ce50aab6`

![image](https://user-images.githubusercontent.com/14177833/228552242-9fdf7029-8f8e-4889-9e01-804f5d6614e7.png)

The parser inside the AzureRM Provider expects `webHooks`:

![image](https://user-images.githubusercontent.com/14177833/228552014-cd7a0e8b-61ea-4fdf-9ca6-158d40d727ec.png)

The team introduced the change with:

https://github.com/hashicorp/terraform-provider-azurerm/commit/821ea0a145254b3c2bfed79bd4e331c499f6ae45
https://github.com/hashicorp/terraform-provider-azurerm/pull/19507

No issue when using Terraform,  because the team added a (silent) state migration.

![image](https://user-images.githubusercontent.com/14177833/228553289-136c85c5-4afe-497f-8b70-cfa35352f488.png)

Pulumi isn't aware of state migrations because it handles the state on it's own. But in such cases this is a real problem, because in the current case, I've to update the Pulumi state manually and correct the casing from `webhooks` to `webHooks`.

**Comment by tmeckel** [comment] 2023-03-29 13:36
@t0yv0 shall I open a new issue on this problem here?

**Comment by t0yv0** [comment] 2023-03-29 13:49
Closing in favor of #923 for remaining issues, thank you!

**Closed by t0yv0** 2023-03-29 13:49 UTC
Labels: resolution/duplicate, kind/bug
