### ISSUE TITLE
Consecutive Pulumi Preview Runs on the Same Stack Return Different Update Plans

### ISSUE THREAD

**Issue by phillipedwards** [pulumi/pulumi-terraform-bridge#722] opened 2022-12-02 22:24 UTC
When running `pulumi preview` consecutively on the same stack, Pulumi is returning different update plans for the same stack. Note, no actual deployment (pulumi up) is occurring during `preview` runs.

Details to come, but the Pulumi Program contains an EKS cluster, K8s resources, and outputted kubeconfig.

Some sample results:
first `preview`
```
    logger.go:34:         + 28 to create
    logger.go:34:         ~ 6 to update
    logger.go:34:         +-4 to replace
```

second `preview`
```
logger.go:34:         + 28 to create
logger.go:34:         ~ 8 to update
logger.go:34:         +-24 to replace
```

The second update plan (with more updates and replacements) appears to be connected to a (possibly non-existent) change in the kubeconfig. It also appears to be connected to the k8s provider requiring an update.

Sample output from the first `preview`
```
  logger.go:34:                 ~ pulumi:providers:kubernetes: (update)
    logger.go:34:                     [id=98d63474-f87c-49ea-afb8-03445afacfdf]
    logger.go:34:                     [urn=urn:pulumi:phil-test::aws-eks::cloud:aws:eks/cluster:Cluster$pulumi:providers:kubernetes::eks-eks-k8s]
    logger.go:34:                   ~ enableServerSideApply: false => true
    logger.go:34:                   ~ version              : "3.20.1" => "3.22.1"``
```

Sample output from the second `preview` when all resources dependent on the provider are to be replaced
```
logger.go:34:                 +-pulumi:providers:kubernetes: (replace)
    logger.go:34:                     [id=98d63474-f87c-49ea-afb8-03445afacfdf]
    logger.go:34:                     [urn=urn:pulumi:phil-test::aws-eks-typescript::cloud:aws:eks/cluster:Cluster$pulumi:providers:kubernetes::eks-eks-k8s]
    logger.go:34:                     enableConfigMapMutable     : false
    logger.go:34:                     enableDryRun               : false
    logger.go:34:                     enableReplaceCRD           : false
    logger.go:34:                   ~ enableServerSideApply      : false => true
    logger.go:34:                   ~ kubeconfig                 : (json) {
    logger.go:34:                       - apiVersion     : "v1"
    logger.go:34:                       - clusters       : [
    logger.go:34:                       -     [0]: {
    logger.go:34:                               - cluster: {
    logger.go:34:                                   - certificate-authority-data: “redacted”
    logger.go:34:                                   - server                    : "https://0ea973621185408cb9b68e9e21a5ac5a.gr7.us-west-2.eks.amazonaws.com/"
    logger.go:34:                                 }
    logger.go:34:                               - name   : "kubernetes"
    logger.go:34:                             }
    logger.go:34:                         ]
    logger.go:34:                       - contexts       : [
    logger.go:34:                       -     [0]: {
    logger.go:34:                               - context: {
    logger.go:34:                                   - cluster: "kubernetes"
    logger.go:34:                                   - user   : "aws"
    logger.go:34:                                 }
    logger.go:34:                               - name   : "aws"
    logger.go:34:                             }
    logger.go:34:                         ]
    logger.go:34:                       - current-context: "aws"
    logger.go:34:                       - kind           : "Config"
    logger.go:34:                       - users          : [
    logger.go:34:                       -     [0]: {
    logger.go:34:                               - name: "aws"
    logger.go:34:                               - user: {
    logger.go:34:                                   - exec: {
    logger.go:34:                                       - apiVersion: "client.authentication.k8s.io/v1beta1"
    logger.go:34:                                       - args      : [
    logger.go:34:                                       -     [0]: "eks"
    logger.go:34:                                       -     [1]: "get-token"
    logger.go:34:                                       -     [2]: "--cluster-name"
    logger.go:34:                                       -     [3]: "eks-cluster-7c1e5ec"
    logger.go:34:                                         ]
    logger.go:34:                                       - command   : "aws"
    logger.go:34:                                       - env       : [
    logger.go:34:                                       -     [0]: {
    logger.go:34:                                               - name : "AWS_PROFILE"
    logger.go:34:                                               - value: "test"
    logger.go:34:                                             }
    logger.go:34:                                       -     [1]: {
    logger.go:34:                                               - name : "KUBERNETES_EXEC_INFO"
    logger.go:34:                                               - value: "client.authentication.k8s.io/v1beta1"
    logger.go:34:                                             }
    logger.go:34:                                         ]
    logger.go:34:                                     }
    logger.go:34:                                 }
    logger.go:34:                             }
    logger.go:34:                         ]
    logger.go:34:                     }
    logger.go:34:      => output<string>
```

**Comment by iwahbe** [comment] 2023-01-23 22:23
@rshade Did you get a repro for this. I'm unable to repro on my and I don't see any obvious problems with `MaxItemsOne: true`.

**Comment by lukehoban** [comment] 2023-01-26 14:54
We unfortunately still don’t have a repro - which continues to slow down progress here. 

@t0yv0 shared a thought in chat that might be another guess at how we could plausibly see “non-determinism” here - not sure this is it - but it’s a least a plausible line of reasoning:

> Here's what strikes me as a possible hypothesis. There's special provider resource p and resources r1..r2 that depend on p. The change modifies p->p'. Under p' semantics r1'..r2' require replacement. However the first preview uses p semantics to calculate the diff, instead of p' semantics. So it doesn't show the required replacement at first. It only "catches up" on the second preview.

**Comment by mikhailshilkov** [comment] 2023-01-27 13:14
I removed p1 since the issue is marked as blocked. Let me know if I'm wrong.

**Comment by thomas11** [comment] 2023-01-27 13:47
Another issue came in via triage, pulumi/pulumi-eks#851, which looks suspiciously similar. Also different results for repeated `preview` runs, also EKS.
FYI @lukehoban, @danielrbradley, @iwahbe

**Closed** 2023-02-01 05:33 UTC
Labels: kind/bug

**Comment by t0yv0** [comment] 2023-02-01 17:08
Recommend upgrading to pulumi-terraform-bridge v3.39.1:

- https://github.com/pulumi/pulumi-eks/issues/851 is definitely reproduced and confirmed fixed by this update
- if the root cause is similar, we should now have a fail-fast message and not indeterminate behavior
- there are also now warnings at `make tfgen` time that help detect statically (https://github.com/pulumi/pulumi-terraform-bridge/pull/775)

As always I hesitate a little calling this closed since I don't think we have reproduced - or have we @iwahbe ? But it seems very likely addressed by the above. Please reopen if this persists after the upgrade to v3.39.1

**Comment by iwahbe** [comment] 2023-02-01 18:43
We don't have a full repro tracing all the way through to Kubernetes. We know from logs that underlying problem for this issue is with a flake in the `certificateAuthority` field of an `aws:eks:Cluster` on repeated preview. Specifically, repeated previews with expected diffs on the cluster `version` field result in the `certificateAuthority` being set to `null`. This is exactly the same as https://github.com/pulumi/pulumi-eks/issues/851, which we can repro and that is now fixed.

Given that we know this bug is present, we know it would cause an update of the Kubernetes provider and the associated mass of resource replaces. I'm confident that this is the same issue as https://github.com/pulumi/pulumi-eks/issues/851.
