### ISSUE TITLE
Bridge upgrade failures related to terraform-exec/tfinstall

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-terraform-bridge#1680] opened 2024-02-09 21:20 UTC
### What happened?

Last round of automated bridge updates ran into trouble with the following repositories with a very similar looking go build failure:

```[tasklist]
- [ ] https://github.com/pulumi/pulumi-splunk/issues/273
- [ ] https://github.com/pulumi/pulumi-github/issues/559
- [ ] https://github.com/pulumi/pulumi-consul/issues/344
- [ ] https://github.com/pulumi/pulumi-cloudamqp/issues/357
- [ ] https://github.com/pulumi/pulumi-alicloud/issues/576
```

The listed repositories are not on the latest bridge.

### Example

See above.

### Output of `pulumi about`

N/A

### Additional context

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2024-02-13 22:48
This is caused by upstream providers using a newer version of `terraform-exec`. `terraform-exec` removed `tfinstall` in v0.16.0, so forcing an upgrade of `terraform-exec` causes the problem. The solution is to pin `terraform-exec` to `v0.15.0`, as we already do in some providers: https://github.com/pulumi/pulumi-akamai/blob/a3b2b1a0523c580e664c0bd092afb9e53d2cc950/provider/go.mod#L12.

**Comment by iwahbe** [comment] 2024-02-13 23:17
I'm resolving these manually for now to finish the bridge upgrade. I don't think we need to address these in an automated way. The issue only effects providers that are using `terraform-plugin-sdk` (v1).

**Closed** 2024-02-13 23:50 UTC
Labels: resolution/fixed, kind/engineering
