### ISSUE TITLE
Deprecation message uses terraform property name

### ISSUE THREAD

**Issue by nesl247** [pulumi/pulumi-terraform-bridge#77] opened 2019-11-20 22:00 UTC
For example: ```warning: urn:pulumi:support::vault::vault:kubernetes/authBackendRole:AuthBackendRole::default verification warning: "policies": [DEPRECATED] use `token_policies` instead```

**Comment by jkodroff** [comment] 2022-03-12 03:50
Based on #442 (where another user is noting that the warning does not include the attribute name), I believe the error message no longer prints the attribute name. Propose closing.

**Comment by guineveresaenger** [comment] 2022-12-07 18:29
Closing as dupe of #6

**Closed by guineveresaenger** 2022-12-07 18:29 UTC
