### ISSUE TITLE
[docs] pulumi import documentation for randomPassword:RandomPassword is wrongly formatted

### ISSUE THREAD

**Issue by bperel** [pulumi/pulumi-terraform-bridge#1224] opened 2023-06-14 15:10 UTC
### What happened?

I am trying to import a RandomPassword resource but it fails, probably because I'm missing an argument in my comment:
```shell
bperel % pulumi import random:index/randomPassword:RandomPassword my-password                             
error: an inline resource must be specified if no converter or import file is used
```
Looking at the [documentation](https://www.pulumi.com/registry/packages/random/api-docs/randompassword/#import) doesn't help because the example doesn't indicate what arguments are expected and is wrongly formatted:
![Screenshot 2023-06-14 at 17 07 08](https://github.com/pulumi/pulumi/assets/1484692/17c679c1-9991-4b5e-ba07-685b7fdc097c)

I had a look at the source code of the documentation and saw [the same formatting issue](https://github.com/pulumi/pulumi-random/blob/d0caab410913aa1cf4bfaf297173b7ac43bf40a1/sdk/nodejs/randomPassword.ts#L35-L41).

### Expected Behavior

I would expect to see what arguments are expected to import a RandomPassword resource

### Steps to reproduce

Check the documentation

### Output of `pulumi about`

N/A

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment] 2023-06-15 14:41
Closing as a duplicate of https://github.com/pulumi/pulumi-random/issues/286

**Closed by iwahbe** 2023-06-15 14:41 UTC
Labels: resolution/duplicate, kind/bug, area/docsgen
